# Generated by Django 5.2.7 on 2026-04-09 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_quantity_gt_zero'),
        ('production', '0001_initial'),
        ('production_lines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productionentry',
            constraint=models.CheckConstraint(condition=models.Q(('rejected_qty__lte', models.F('produced_qty'))), name='production_rejected_lte_produced'),
        ),
    ]
