# Generated by Django 5.2.7 on 2026-04-09 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_order_quantity_gt_zero'),
        ('production_lines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_stage', models.CharField(choices=[('inline', 'Inline'), ('endline', 'Endline'), ('final', 'Final')], max_length=20)),
                ('date', models.DateField()),
                ('checked_qty', models.PositiveIntegerField()),
                ('passed_qty', models.PositiveIntegerField(default=0)),
                ('defective_qty', models.PositiveIntegerField(default=0)),
                ('rejected_qty', models.PositiveIntegerField(default=0)),
                ('rework_qty', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('barcode_value', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspections', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspections', to='orders.order')),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='production_lines.productionline')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityInspectionDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('defect_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_defects', to='quality.defecttype')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='quality.qualityinspection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='qualityinspection',
            constraint=models.CheckConstraint(condition=models.Q(('checked_qty__gt', 0)), name='quality_checked_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='qualityinspection',
            constraint=models.CheckConstraint(condition=models.Q(('rejected_qty__lte', models.F('defective_qty'))), name='quality_rejected_lte_defective'),
        ),
        migrations.AddConstraint(
            model_name='qualityinspection',
            constraint=models.CheckConstraint(condition=models.Q(('rework_qty__lte', models.F('defective_qty'))), name='quality_rework_lte_defective'),
        ),
        migrations.AddConstraint(
            model_name='qualityinspectiondefect',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quality_inspection_defect_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='qualityinspectiondefect',
            constraint=models.UniqueConstraint(fields=('inspection', 'defect_type'), name='quality_inspection_defect_unique'),
        ),
    ]
