# Generated by Django 5.2.7 on 2026-04-09 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_order_quantity_gt_zero'),
        ('production_lines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker_code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('skill_type', models.CharField(blank=True, max_length=80)),
                ('barcode_value', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='production_lines.productionline')),
            ],
            options={
                'ordering': ['name', 'worker_code'],
            },
        ),
        migrations.CreateModel(
            name='WorkerProductivityEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('target_qty', models.PositiveIntegerField()),
                ('actual_qty', models.PositiveIntegerField(default=0)),
                ('rework_qty', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_productivity_entries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_productivity_entries', to='orders.order')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_productivity_entries', to='production_lines.productionline')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productivity_entries', to='productivity.worker')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_qty__gt', 0)), name='worker_productivity_target_gt_zero'), models.CheckConstraint(condition=models.Q(('rework_qty__lte', models.F('actual_qty'))), name='worker_rework_lte_actual')],
            },
        ),
    ]
