# Generated by Django 5.2.7 on 2026-04-09 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_code', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('style_name', models.CharField(max_length=160)),
                ('style_code', models.CharField(blank=True, max_length=120)),
                ('quantity', models.PositiveIntegerField()),
                ('target_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_date', models.DateField()),
                ('current_stage', models.CharField(choices=[('cutting', 'Cutting'), ('stitching', 'Stitching'), ('qc', 'QC'), ('packing', 'Packing'), ('dispatch', 'Dispatch')], default='cutting', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='buyers.buyer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
