# Generated by Django 5.2.7 on 2026-04-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('store_manager', 'Store Manager'), ('production_supervisor', 'Production Supervisor'), ('quality_inspector', 'Quality Inspector'), ('planner', 'Planner'), ('supervisor', 'Supervisor'), ('viewer', 'Viewer')], default='viewer', max_length=30),
        ),
    ]
