# Generated by Django 5.2.7 on 2026-04-09 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_order_quantity_gt_zero'),
        ('production_lines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('planned_daily_target', models.PositiveIntegerField()),
                ('planned_total_qty', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_plans', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_plans', to='orders.order')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_plans', to='production_lines.productionline')),
            ],
            options={
                'ordering': ['-planned_start_date', '-created_at'],
            },
        ),
    ]
